permalink:  pretty
markdown: kramdown
highlighter: rouge
name: Robert Heaton | Blog
description: 'Software engineer. One-track lover down a two-way lane'
url: https://robertheaton.com
feedburner_id: robertheaton
future: true
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 20
permalink: "/:title/"
sass:
  sass_dir: assets
  style: :compressed
