permalink:   pretty
pygments: true
markdown:    rdiscount
rdiscount:
  extensions: [smart]
name: Robert Heaton
description: 'Co-founder @Copyin.com. Lies, damn lies and startups.'
url: http://robertheaton.com
auto: true
feedburner_id: robertheaton