permalink:   pretty
highlighter: pygments
markdown:    rdiscount
rdiscount:
  extensions: [smart]
name: Robert Heaton
description: 'Software engineer. One-track lover down a two-way lane'
url: http://robertheaton.com
auto: true
feedburner_id: robertheaton
future: true
gems: 
  - jekyll-redirect-from
