permalink:  pretty
markdown: kramdown
highlighter: rouge
name: Robert Heaton | Blog
description: 'Software engineer. One-track lover down a two-way lane'
url: https://robertheaton.com
auto: true
feedburner_id: robertheaton
future: true
gems:
  - jekyll-redirect-from
  - jekyll-paginate
paginate: 20
